--------------------------------------------------------
--  File created - Tuesday-December-17-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UZIVATELE
--------------------------------------------------------

  CREATE TABLE "ST55409"."UZIVATELE" 
   (	"ID_UZIVATELE" NUMBER(10,0), 
	"LOGIN" VARCHAR2(20 BYTE), 
	"HESLO" VARCHAR2(20 BYTE), 
	"JMENO" VARCHAR2(20 BYTE), 
	"PRIJMENI" VARCHAR2(20 BYTE), 
	"POZNAMKA" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"BLOKACE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table UZIVATELE_SP
--------------------------------------------------------

  CREATE TABLE "ST55409"."UZIVATELE_SP" 
   (	"ID_UZIVATELE_SP" NUMBER(6,0), 
	"ID_UZIVATELE" NUMBER(6,0), 
	"ID_ST_PLANU" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Table ZPRAVY
--------------------------------------------------------

  CREATE TABLE "ST55409"."ZPRAVY" 
   (	"ID_ZPRAVY" NUMBER(*,0), 
	"CASOVE_RAZITKO" TIMESTAMP (6), 
	"OBSAH" CLOB, 
	"POZNAMKA" VARCHAR2(120 BYTE), 
	"PREDMET" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" 
 LOB ("OBSAH") STORE AS SECUREFILE (
  TABLESPACE "STUDENTI" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index SYS_C0038890
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."SYS_C0038890" ON "ST55409"."UZIVATELE" ("ID_UZIVATELE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index UZIVATEL_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."UZIVATEL_UNIQUE" ON "ST55409"."UZIVATELE" ("LOGIN", "HESLO", "EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index UZIV_JMENO__2
--------------------------------------------------------

  CREATE BITMAP INDEX "ST55409"."UZIV_JMENO__2" ON "ST55409"."UZIVATELE" ("PRIJMENI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index SYS_C0041991
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."SYS_C0041991" ON "ST55409"."UZIVATELE_SP" ("ID_UZIVATELE_SP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Index SYS_C0041982
--------------------------------------------------------

  CREATE UNIQUE INDEX "ST55409"."SYS_C0041982" ON "ST55409"."ZPRAVY" ("ID_ZPRAVY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI" ;
--------------------------------------------------------
--  DDL for Trigger USER_DELETE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ST55409"."USER_DELETE" 
BEFORE DELETE ON UZIVATELE
FOR EACH ROW 
DECLARE 
PRAGMA AUTONOMOUS_TRANSACTION;
CURSOR cur_1 
IS
SELECT id_role from ROLE_UZIVATELE
WHERE ROLE_UZIVATELE.ID_UZIVATELE = :OLD.ID_UZIVATELE AND ID_ROLE = 88;
v_role_uz  cur_1%ROWTYPE;
BEGIN
DELETE FROM UDALOSTI UD
WHERE UD.ID_UZIVATELE = :OLD.ID_UZIVATELE;
DELETE FROM IMAGES IM
WHERE IM.ID_UZIV = :OLD.ID_UZIVATELE;
DELETE FROM UZIVATELE_SP UZ_SP
WHERE UZ_SP.ID_UZIVATELE = :OLD.ID_UZIVATELE;
DELETE FROM ROLE_UZIVATELE R_UZ
WHERE R_UZ.ID_UZIVATELE = :OLD.ID_UZIVATELE;
BEGIN 
OPEN cur_1;
LOOP
FETCH cur_1 INTO v_role_uz;
IF cur_1%NOTFOUND  then
DBMS_OUTPUT.PUT_LINE('Nothing to deleete');
EXIT;
ELSE 
DELETE from SKUPINA_CLENY SK_CL
WHERE SK_CL.ID_UZIVATELE = :OLD.ID_UZIVATELE;
END IF;
END LOOP;
CLOSE cur_1;
END;
COMMIT;
END;
/
ALTER TRIGGER "ST55409"."USER_DELETE" ENABLE;
--------------------------------------------------------
--  Constraints for Table UZIVATELE
--------------------------------------------------------

  ALTER TABLE "ST55409"."UZIVATELE" ADD CONSTRAINT "UZIVATEL_UNIQUE" UNIQUE ("LOGIN", "HESLO", "EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
  ALTER TABLE "ST55409"."UZIVATELE" MODIFY ("ID_UZIVATELE" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."UZIVATELE" MODIFY ("LOGIN" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."UZIVATELE" ADD PRIMARY KEY ("ID_UZIVATELE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table UZIVATELE_SP
--------------------------------------------------------

  ALTER TABLE "ST55409"."UZIVATELE_SP" MODIFY ("ID_UZIVATELE_SP" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."UZIVATELE_SP" MODIFY ("ID_UZIVATELE" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."UZIVATELE_SP" MODIFY ("ID_ST_PLANU" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."UZIVATELE_SP" ADD PRIMARY KEY ("ID_UZIVATELE_SP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZPRAVY
--------------------------------------------------------

  ALTER TABLE "ST55409"."ZPRAVY" MODIFY ("ID_ZPRAVY" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."ZPRAVY" MODIFY ("CASOVE_RAZITKO" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."ZPRAVY" MODIFY ("OBSAH" NOT NULL ENABLE);
  ALTER TABLE "ST55409"."ZPRAVY" ADD PRIMARY KEY ("ID_ZPRAVY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTI"  ENABLE;
  ALTER TABLE "ST55409"."ZPRAVY" MODIFY ("PREDMET" NOT NULL ENABLE);
